# Generated by Django 4.0.3 on 2022-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0005_player_count_cup_player_height_player_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='base',
        ),
        migrations.RemoveField(
            model_name='player',
            name='count_cup',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Стаж лет'),
        ),
    ]
