# Generated by Django 4.0.3 on 2022-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0008_alter_game_options_alter_game_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=11, verbose_name='Дата'),
        ),
    ]
