# Generated by Django 4.0.3 on 2022-05-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0009_alter_game_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=11, verbose_name='Гендер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('date_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=100, null=True, verbose_name='Гражданство')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
