# Generated by Django 4.0.3 on 2022-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0012_anamnesis_info1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='time1',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
    ]
